### ISSUE TITLE
Regrets Reporter covers functional button in mini player

### ISSUE THREAD

**Issue by ChrisTheCat** [mozilla-extensions/regrets-reporter#32]
When I move a video to the mini player, Regrets Reporter covers up the button at top right of the mini player that allows you to return to regular view.

**Comment by ryoakg** [comment]
I came across it too.

Here is a workaround, you might have already fixed it yourself though.

Put following in your [Stylus](https://github.com/openstyles/stylus) collection.
```css
@-moz-document domain("www.youtube.com") {

.miniplayer [id^="regrets_reporter__video_"].mrr-injected-btn{
	top: 40px;
}

}
```
